Repository Glavin001/atom-beautify, pull requests merged in 2018-05, with the labels that each got.

#2087 Basic Implement of Blade Template
  .travis.yml
  CHANGELOG.md
  README.md
  atom-packages.txt
  docs/options.md
  examples/simple-jsbeautifyrc/blade/expected/test.blade.php
  examples/simple-jsbeautifyrc/blade/original/test.blade.php
  package.json
  spec/beautify-languages-spec.coffee
  src/beautifiers/js-beautify.coffee
  src/languages/blade.coffee
  src/languages/index.coffee
  src/options.json
Labels: add-language

#2129 Fix Docker Executable with optional Executable, PHP-CS-Fixer
  CHANGELOG.md
  src/beautifiers/executable.coffee
  src/beautifiers/php-cs-fixer.coffee
Labels: bug

#2086 fixed: package.json repository compatible with apm and npm
  package.json
Labels: stale

#2096 Workaround for Rubocop string split for Windows
  src/beautifiers/rubocop.coffee
Labels: bug

#2141 Require path in phpcbf
  src/beautifiers/phpcbf.coffee
Labels: bug
