Repository Glavin001/atom-beautify, pull requests merged in 2018-03, with the labels that each got.

#2047 Add prettier beautifier and bracket_spacing option
  CHANGELOG.md
  README.md
  docs/options.md
  package.json
  src/beautifiers/coffee-formatter.coffee
  src/beautifiers/index.coffee
  src/beautifiers/prettier.coffee
  src/beautifiers/typescript-formatter.coffee
  src/languages/javascript.coffee
  src/languages/tsx.coffee
  src/languages/typescript.coffee
  src/options.json
Labels: add-beautifier, add-beautifier-option, high priority

#1776 Improved Rubocop configuration and temp files
  CHANGELOG.md
  src/beautifiers/rubocop.coffee
Labels: enhancement, high priority

#1941 Add MagicPython grammar to python language
  .travis.yml
  CHANGELOG.md
  README.md
  src/languages/python.coffee
  src/options.json
Labels: add-extension-or-grammar

#1980 Added VHDL Support via Emacs
  docs/options.md
  examples/nested-jsbeautifyrc/vhdl/expected/test.vhd
  examples/nested-jsbeautifyrc/vhdl/original/test.vhd
  package.json
  src/beautifiers/index.coffee
  src/beautifiers/vhdl-beautifier/emacs-vhdl-formating-script.lisp
  src/beautifiers/vhdl-beautifier/index.coffee
  src/languages/index.coffee
  src/languages/vhdl.coffee
  src/options.json
Labels: add-beautifier, add-language

#1959 Added the option to indent Bash scripts with tabs
  CHANGELOG.md
  src/beautifiers/beautysh.coffee
  src/languages/bash.coffee
  src/options.json
Labels: add-beautifier-option

#2000 Add GN beautifier
  CHANGELOG.md
  README.md
  docs/options.md
  examples/nested-jsbeautifyrc/gn/expected/test.gn
  examples/nested-jsbeautifyrc/gn/original/test.gn
  package.json
  src/beautifiers/gn.coffee
  src/beautifiers/index.coffee
  src/languages/gn.coffee
  src/languages/index.coffee
  src/options.json
Labels: add-beautifier, add-language

#2019 Change node-uuid to uuid, prepublish to prepare
  package.json
  src/beautifiers/index.coffee
Labels: update-dependency

#2024 Change from coffee-script to coffeescript for npm package
  package.json
  script/build-options.js
Labels: update-dependency

#2033 Add Vue support to ESLint Fixer beautifier
  CHANGELOG.md
  README.md
  docs/options.md
  package.json
  src/beautifiers/eslint.coffee
  src/options.json
Labels: enhancement

#2061 Disable gn and verilog CI tests for now
  examples/nested-jsbeautifyrc/gn/original/_test.gn
  examples/nested-jsbeautifyrc/verilog/original/_test.v
Labels: bug

#2060 Upgrade prettier to 1.11
  CHANGELOG.md
  package-lock.json
  package.json
Labels: update-dependency

#2063 Fix package.json repository.url; fix travis build
  .travis.yml
  CHANGELOG.md
  package.json
Labels: enhancement

#2069 Update Rubocop to be an executable
  README.md
  docs/options.md
  examples/nested-jsbeautifyrc/ruby/expected/test.rb
  examples/nested-jsbeautifyrc/ruby/original/test.rb
  package.json
  src/beautifiers/rubocop.coffee
  src/options.json
Labels: bug, enhancement

#2071 Fix to send parser to prettier API properly
  src/beautifiers/prettier.coffee
Labels: bug, high priority

#2068 Fix #1790. Fix Lua indentation format bug
  examples/simple-jsbeautifyrc/lua/expected/test.lua
  src/beautifiers/lua-beautifier/beautifier.coffee
Labels: bug

#2064 Fix "Reindent" option for sqlformat.
  CHANGELOG.md
  src/beautifiers/sqlformat.coffee
Labels: bug
